kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: plugins/hugo
    environment:
      PLUGIN_HUGO_VERSION: 0.83.1
      PLUGIN_VALIDATE: true
  - name: deploy
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /public
      PLUGIN_DEST_DIR: /
      PLUGIN_MIRROR_OPTS: -e
      PLUGIN_CLEAN_DIR: false
    when:
      event:
        exclude:
          - pull_request
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
        - success
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main
