---
kind: pipeline
type: docker
name: build

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  - name: build
    image: plugins/hugo
    environment:
      PLUGIN_HUGO_VERSION: 0.76.5
      PLUGIN_EXTENDED: true
      PLUGIN_VALIDATE: true
  - name: deploy
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: username
      FTP_PASSWORD:
        from_secret: password
      PLUGIN_HOSTNAME:
        from_secret: ftphost
      PLUGIN_SRC_DIR: /public
      PLUGIN_DEST_DIR: /
      PLUGIN_MIRROR_OPTS: -e
      PLUGIN_CLEAN_DIR: false
    when:
      event:
        exclude:
          - pull_request

trigger:
  branch:
    include:
      - main
---
kind: signature
hmac: d5142fff620c36599a73e6ae01a593e191545a1b8ac734a753fc332600237d9b

...
