# Site settings
baseurl = "/"
languageCode = "de-de"
defaultContentLanguage = "de"
title = "Projekt Alarmdisplay"
theme = "syna"

enableGitInfo = true
version = "0.17.2"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# Google Analytics tracking
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[params]
  name = "Projekt Alarmdisplay"
  description = "Informationssystem für Hilfsorganisationen"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#aa050d"
    secondary = "#bdcddd"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# footer/footer_social menus are displayed in footer fragment.
# copyright_footer menus are displayed in copyright fragment
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "https://docs.alarmdisplay.org"
  name = "Docs"
  weight = 20

[[menu.footer]]
  url = "https://syna.okkur.org/demo"
  name = "Getting Started"
  weight = 10

[[menu.footer]]
  url = "https://about.okkur.org/"
  name = "About Okkur Labs"
  weight = 20

[[menu.footer_social]]
  weight = 30
  name = "github"
  url = "https://github.com/alarmdisplay"
  pre = "fab fa-github fa-stack-2x"

[[menu.footer_social]]
  weight = 40
  name = "twitter"
  url = "https://twitter.com/alarm_display"
  pre = "fab fa-twitter"

