baseURL = "https://alarmdisplay.org/"
languageCode = "de-de"
title = "Projekt Alarmdisplay"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 6
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Informationssystem für Hilfsorganisationen"
  facebook = ""
  twitter = "https://twitter.com/alarm_display"
  instagram = ""
  youtube = ""
  github = "https://github.com/alarmdisplay"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "index.xml"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "hero.jpeg"
  recent_posts_number = 2

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
